version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./database.env
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
    ports: 
      - "27017:27017"
    networks: 
      - spring
    
  udemy_sbhrestijwts3msqlmdb5:
    build:
      context: ./
      dockerfile: Dockerfile
    image: maven:3-openjdk-15-slim
    container_name: udemy_sbhrestijwts3msqlmdb5
    depends_on: 
      - mongo
    ports: 
      - "8080:8080"
    env_file:
      - ./dev.env
    networks: 
      - spring

networks:
  spring:
    ipam:
      driver: default
      config:
        - subnet: 10.172.170.0/24
