spring:
  data:
    mongodb:
      uri: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: ${MONGO_AUTHDATABASE}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}