spring:
  data:
    mongodb:
      # uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTHDATABASE}
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      authentication-database: ${MONGO_AUTHDATABASE}
